### PR TITLE
Feature/user receives message

### PR DESCRIPTION
**Pull request by aakyol**
Could everyone make sure to do this:

- Run locally and test against the acceptance criteria.

The acceptance criteria is in the card: https://trello.com/c/Sg9ZTv6W/19-user-can-receive-a-message

### CODE REVIEW

**Review by aakyol — COMMENTED** [review]
This still has the unfinished CurrentChatActivityTest. If you think this should be removed/ transported to UITest branch, then we should @VJftw

**Review by VJftw — APPROVED** [review]
Instead of requesting changes, I felt it would be quicker just for me to get them done as we do need to start on encryption ASAP. The most important change was this: https://github.com/MonarchsofCoding/chitchat/commit/09c616844866672e270dcd5ae27f6475507fae87

**Review by VJftw — CHANGES_REQUESTED** [review]
Fix the E2E tests :'(

**Comment by VJftw** [comment]
This is one behemoth of a PR with a couple extra features:
 - ui tests (incomplete) - really big
 - better deployment on the backend

I think we should have kept these on separate branches and merged them in after they were complete with their own pull requests, and kept back-merging when we needed to. We can talk about this in our final report, but need to be more careful about this happening again.

**Review by VJftw — APPROVED** [review]

**Review by FareedQasim — APPROVED** [review]

**Review by AigerimSerikbekova — APPROVED** [review]

**Review by spiroskous — APPROVED** [review]
The only thing just to mention is that you receive the message when the user is actually online . I send a message to user B . User B receives that only if it is online if it is not and log in after that then he does not have any notification.

**Review by Ozhan-Azizi — APPROVED** [review]

**Pull request merged**
